# Generated by Django 4.0.4 on 2022-10-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=50)),
                ('fami', models.CharField(max_length=50)),
                ('lavozimi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('maydoni', models.FloatField()),
                ('malumot', models.CharField(max_length=800)),
                ('rasm', models.ImageField(upload_to='media')),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=50)),
                ('fam', models.CharField(max_length=50)),
                ('rasmi', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=70)),
                ('eski_narxi', models.IntegerField()),
                ('yangi_narxi', models.IntegerField()),
                ('xonalar', models.IntegerField()),
                ('yuvinish_xonasi', models.IntegerField()),
                ('maydon', models.FloatField()),
                ('rasm', models.ImageField(upload_to='media')),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
