# Generated by Django 4.0.4 on 2022-10-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agents',
        ),
    ]
