# Generated by Django 4.0.4 on 2022-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_delete_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=50)),
                ('fami', models.CharField(max_length=50)),
                ('lavozimi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='media')),
            ],
        ),
    ]
