# Generated by Django 4.0.4 on 2022-10-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='malumot',
            field=models.CharField(default=0, max_length=800),
            preserve_default=False,
        ),
    ]
