# Generated by Django 4.0.4 on 2022-10-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_clients_malumot'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='lavozimi',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
